definitions:
  steps:
    - step: &deploy
        name: Tag commit and push
        trigger: automatic
        script:
          - git tag ${BITBUCKET_BUILD_NUMBER}
          - git push origin --tags

pipelines:
  branches:
    develop:
      - step: *deploy
    master:
      - step:
          name: Autostep to avoid BB errors
          trigger: automatic
          script:
            - echo "Stubbing for manual build"
      - step:
          <<: *deploy
          trigger: manual
