# base vars
env: development
region: us-west-2
deploy_bucket: development-clear-lake-sls-deploy

# app settings:
app_name: "versionator-ui"
app_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}"
app_log_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}-logs"
app_domain_alias: "versionator.data-dev.clearcollateral.com"
app_cert: "arn:aws:acm:us-east-1:758725036624:certificate/af706b0f-34e3-4880-becb-39f2ba354a2f"
app_acl: "arn:aws:wafv2:us-east-1:758725036624:global/webacl/StackSet-CC-WAF-IP-0fdde5ab-0926-42b0-b144-4ef32661d2ed-us-east-1-WAF/6ce3045d-9b02-43b0-8e84-2b261335fb92"

# ssm derived
app_hosted_zone: '{{resolve:ssm:/data/dev/route53/hosted_zone/data-dev.clearcollateral.com:1}}'


