# base vars
env: production
region: us-west-2
deploy_bucket: clear-lake-artifacts-${self:custom.vars.env}

# app settings:
app_name: "versionator-ui"
app_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}"
app_log_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}-logs"
app_domain_alias: "versionator.data-npe.clearcollateral.com"
app_cert: "arn:aws:acm:us-east-1:736018059497:certificate/de297d65-afd1-49cb-a05a-c96721250f00"
app_acl: "arn:aws:wafv2:us-east-1:736018059497:global/webacl/StackSet-CC-WAF-IP-917d2e91-930b-449a-ae2d-1e28bd57a29f-us-east-1-WAF/90d14a4c-38cb-4c57-87fa-db4e99ae827f"

# ssm derived
app_hosted_zone: '{{resolve:ssm:/data/npe/route53/hosted_zone/data-npe.clearcollateral.com:1}}'
