# base vars
env: test
region: us-west-2
deploy_bucket: development-clear-lake-sls-deploy

# app settings:
app_name: "versionator-ui"
app_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}"
app_log_bucket: "${self:custom.vars.env}-clear-lake-${self:custom.vars.app_name}-logs"
app_domain_alias: "versionator.data-qa.clearcollateral.com"
app_cert: "{{resolve:ssm:/ss/qa/acm/us-east-1/ss-qa.clearcollateral.com:1}}"
app_acl: "arn:aws:wafv2:us-east-1:447582771975:global/webacl/StackSet-CC-WAF-IP-30a690e5-bb75-49ee-9018-bfbe7758acec-us-east-1-WAF/447f395c-65a0-4aef-90de-17bbf9b8bb1f"

# ssm derived
app_hosted_zone: '{{resolve:ssm:/data/qa/route53/hosted_zone/data-qa.clearcollateral.com:1}}'
